spring.graphql.graphiql.enabled=true
spring.threads.virtual.enabled=true
server.port=8081



# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/books_service
spring.datasource.username=docker_usr
spring.datasource.password=docker_pwd


# JPA / Hibernate settings
# 'update' automatically creates/updates tables based on your Java records/classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/books_catalog/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/books_catalog
